# Generated by Django 4.1 on 2022-08-06 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productsName', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(default=1, upload_to='')),
                ('factoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.factoryname')),
            ],
        ),
    ]
